### ISSUE TITLE
establishmentMeans and degreeOfEstablisment

### ISSUE THREAD

**Issue by ManonGros** [gbif/vocabulary#74]
DegreeOfEstablishment is a new vocabulary and should be created according to [the spec](http://rs.tdwg.org/dwcdoe/values.htm) 

For the establishmentMeans, we have a file of verbatim values to edit: https://drive.google.com/file/d/1wj6C9x2JfX03qnqwwxoPivCOiACgH_Hk/view?usp=sharing

**It contains:**

- the list of existing concepts
- a list of the values already mapped to the concepts (they are all in the **Hidden** sheet/tab for now)
- the GBIF verbatim values for this field that appear more than 10,000 times or in 5 or more datasets

Please check instructions here: https://github.com/gbif/vocabulary/issues/70

**NB**: For this Vocabulary you ~can consider adding any missing~ will only use the concepts that are part of TDWG establishmentMeans controlled concept scheme: http://rs.tdwg.org/dwcem/values.htm

**Comment by timrobertson100** [comment]
@ManonGros I'd like to do this, please.

**Comment by timrobertson100** [comment]
I have a call with @qgroom to introduce this tomorrow and go over the work, hoping to have him approve the result.

**Comment by timrobertson100** [comment]
The spreadsheet is complete with input from @qgroom.

I will load it into GBIF dev first to verify the scripts and then into the gbif-uat server and leave the scripts and attach the CSV files used in a comment here.

Since this goes with a new vocabulary (i.e. no verbatim data to map) for degreeOfEstablishment I will also prepare files for that. Both are necessary to complete the work for https://github.com/gbif/portal-feedback/issues/3257

**Comment by timrobertson100** [comment]
EstablishmentMeans is now in the UAT vocab server https://registry.gbif-uat.org/vocabulary/EstablishmentMeans/concepts

Imported with the attached CSVs and the following:

```
java -jar vocabulary-importer-0.37-20210323.153852-9.jar --vocabularyName EstablishmentMeans \
--vocabularyLabelEN "Establishment Means" \
--vocabularyDefinitionEN "Provides the controlled vocabulary for information about whether an organism or organisms have been introduced to a given place and time through the direct or indirect activity of modern humans. The Establishment Means Controlled Vocabulary provides terms that should be used as values for dwc:establishmentMeans and dwciri:establishmentMeans." \
--conceptsPath "/tmp/establishmentMeans/Concepts.txt" \
--hiddenLabelsPath "/tmp/establishmentMeans/Hidden.txt" \
--csvDelimiter ";" \
--apiUrl https://api.gbif-uat.org/v1/ \
--apiUser trobertson@gbif.org \ 
--apiPassword ....
```
[Concepts.txt](https://github.com/gbif/vocabulary/files/6191231/Concepts.txt)
[Hidden.txt](https://github.com/gbif/vocabulary/files/6191230/Hidden.txt)

**Comment by timrobertson100** [comment]
These are now both in production https://registry.gbif.org/vocabulary/search 
Thanks to @qgroom for assisting.

**Comment by leobuitrago2** [comment]
This is great @timrobertson100 and @qgroom, congrats! Could we open this issue again, just to add the labels and definitions in Spanish, please?

**Comment by ManonGros** [comment]
@leobuitrago2 I think the edits have to be done directly in the registry now: https://registry.gbif.org/vocabulary/search
@timrobertson100 could you confirm?

**Comment by timrobertson100** [comment]
Thanks, @leobuitrago2 

I chose to push these through because they are small, I wanted to add URIs that the import tool didn't support, and I wanted us to get some experience in editing in the UI so we can identify issues that need solved using small "safe" vocabularies that are not currently used.

Can you please self-assign #93 and #94?
